### DISCUSSION TITLE
Help unit testing v3 multipart/form-data with "Missing boundary in multipart"

### DISCUSSION THREAD

**Discussion by alanbchristie** [spec-first/connexion#1964] [Q&A] [answered]
I'm moving from connexion 2 to connexion 3 (`3.1.0`) and I have "**Missing boundary in multipart**" errors on my OpenAPI endpoints that expect "multipart/form-data".

In v2 unit-testing (which uses `requests`) I didn't need to do anything special here but in v3 I seem to be frustrated at not being able to get past **boundary** exceptions in the client and the server. Here's my setup, where I'm using the connexion test_client() (which, in v3, uses `httpx` rather than `requests`): -

## The OpenAPI endpoint body definition
This is the endpoint body definition for a **POST** at `/asset` (descriptions have been removed to reduce space): -

```yaml
asset_post_body:
  required: true
  content:
    multipart/form-data:
      schema:
        type: object
        properties:
          name:
            type: string
            maxLength: 80
            pattern: ^[a-z0-9-]{1,63}$
          content_file:
            type: string
            format: binary
          content_string:
            type: string
          scope:
            type: string
            enum:
            - USER
            - PRODUCT
            - UNIT
            - ORGANISATION
            - GLOBAL
          scope_id:
            type: string
          secret:
            type: boolean
        required:
        - name
        - scope
        - secret
```

## The unit test
Here an excerpt of a test using the above endpoint. The key elements here are the `headers` and `data`: -

> Assume that the _test client_ is setup correctly because unit tests that do not use Form Data are working

```python
HEADERS_FORM = {'Accept': 'application/json',
                'Content-Type': 'multipart/form-data'}

def test_create_global_secret_asset(client):
    # Arrange
    data = {'name': 'test-asset',
            'content_string': 'secret',
            'scope': 'GLOBAL',
            'secret': True}

    # Act
    response = client.post(Config.API_BASE_PATH + '/asset', headers=HEADERS_FORM, data=data)

    # Assert
    assert response.status_code == 201
    r_data = response.json()
    assert len(r_data) == 1
    assert 'id' in r_data
```

## What happens?
Although this is modified for the v3 response (where `.json` in the response becomes `.json()`) it's essentially the same code that tested the v2 implementation: -

- It sets up the required `data` payload
- It sets the expected `Accept` and `Content-Type` header values

But, when it's run I get a **KeyError** from the underlying `starlette/formparsers.py` module: -

```
ERROR    connexion.middleware.exceptions:exceptions.py:108 MultiPartException('Missing boundary in multipart.')
Traceback (most recent call last):
  File "[...]/lib/python3.12/site-packages/starlette/formparsers.py", line 236, in parse
    boundary = params[b"boundary"]
               ~~~~~~^^^^^^^^^^^^^
KeyError: b'boundary'
```

So there's a missing boundary.

Fine - but why is that my problem?

In the v2 implementation's Swagger the generated **cURL** looks like the following. It does not define a boundary either (here the actual URL replaced by `[...]`): -

```bash
curl -X 'POST' \
  'https://[...]/asset' \
  -H 'accept: application/json' \
  -H 'Content-Type: multipart/form-data' \
  -F 'content_string=secret' \
  -F 'name=test-asset' \
  -F 'scope=GLOBAL' \
  -F 'secret=true'
```
