### ISSUE TITLE
validation error: None is not of type 'array'

### ISSUE THREAD

**Issue by YunfanChen** [spec-first/connexion#1011]
### Description
When I define a parameter in swagger.yaml like this:
```
- name: "alert_events"
          in: "body"
          description: "The list of alert events"
          required: true
          schema:
            type: "array"
            items: 
              type: "string"
```
And the error occurs when I pass a list of string to this parameter.

By the way, when I set this parameter like this: (add **style:"form"** to it)
```
- name: "alert_events"
          in: "body"
          description: "The list of alert events"
          style: "form"
          required: true
          schema:
            type: "array"
            items: 
              type: "string"
```
The swagger editor shows Structural error at paths./model/{name}/get_redpoints.get.parameters.2 should NOT have additional properties additionalProperty: style
<img width="685" alt="image" src="https://user-images.githubusercontent.com/28001172/62283289-cfb56d80-b483-11e9-948e-8a7e7c69ee0f.png">

Which also confused me.

### Expected behaviour
Give a list of string, it receive successful and print out.

### Actual behaviour
When I pass "X1","X2"
Raise an error :
```
2019-08-01 09:18:59 connexion.decorators.validation ERROR    http://localhost:9100/v1/model/Model1/get_redpoints?tenantId=T1 validation error: None is not of type 'array'
2019-08-01 09:18:59 werkzeug INFO     172.17.0.1 - - [01/Aug/2019 09:18:59] "GET /v1/model/Model1/get_redpoints?tenantId=T1 HTTP/1.1" 400 -
```
Seems it pass nothing to the parameter.
And the Curl:
```
curl -X GET --header 'Content-Type: application/json' --header 'Accept: application/problem+json' --header 'userId: a' --header 'apiKey: a' -d '"X1","X2"' 'http://localhost:9100/v1/model/Model1/get_redpoints?tenantId=T1'
```

### Steps to reproduce
<img width="956" alt="image" src="https://user-images.githubusercontent.com/28001172/62283200-97159400-b483-11e9-85cd-334b78e5409b.png">
<img width="961" alt="image" src="https://user-images.githubusercontent.com/28001172/62283210-9e3ca200-b483-11e9-9331-71775b057045.png">

### Additional info:

Output of the commands:
```
2019-08-01 09:18:59 connexion.decorators.validation ERROR    http://localhost:9100/v1/model/Model1/get_redpoints?tenantId=T1 validation error: None is not of type 'array'
2019-08-01 09:18:59 werkzeug INFO     172.17.0.1 - - [01/Aug/2019 09:18:59] "GET /v1/model/Model1/get_redpoints?tenantId=T1 HTTP/1.1" 400 -
```

- `python --version` 3.5
- `pip show connexion | grep "^Version\:"` connexion == 2.2.0
