### ISSUE TITLE
Failed validating 'enum' lambda not being caught

### ISSUE THREAD

**Issue by ConstantinoSchillebeeckxSimpleRose** [spec-first/connexion#1039]
### Description

I've deployed to AWS lambda using [serverless](https://serverless.com) and the app is not able to catch `Failed validating 'enum' in schema['items']` errors. 

🔥 Note that it does work as expected when testing locally.

### Expected behaviour

Response should look like
```json
{
detail: "'foo2' is not one of ['foo', 'bar'] Failed validating 'enum' in schema['items']: {'enum': ['foo', 'bar'], 'type': 'string'} On instance[0]: 'foo2'",
status: 400,
title: "Bad Request",
type: "about:blank"
}
```

### Actual behaviour

Actual response is
```
ewogICJkZXRhaWwiOiAiJ2ZvbzInIGlzIG5vdCBvbmUgb2YgWydmb28nLCAnYmFyJ11cblxuRmFpbGVkIHZhbGlkYXRpbmcgJ2VudW0nIGluIHNjaGVtYVsnaXRlbXMnXTpcbiAgICB7J2VudW0nOiBbJ2ZvbycsICdiYXInXSwgJ3R5cGUnOiAnc3RyaW5nJ31cblxuT24gaW5zdGFuY2VbMF06XG4gICAgJ2ZvbzInIiwKICAic3RhdHVzIjogNDAwLAogICJ0aXRsZSI6ICJCYWQgUmVxdWVzdCIsCiAgInR5cGUiOiAiYWJvdXQ6YmxhbmsiCn0K
```

CloudWatch logs show
```
START RequestId: 3439d067-ba62-415c-9764-fa8a032afa27 Version: $LATEST
END RequestId: 3439d067-ba62-415c-9764-fa8a032afa27
REPORT RequestId: 3439d067-ba62-415c-9764-fa8a032afa27 Duration: 3.10 ms Billed Duration: 100 ms Memory Size: 1024 MB Max Memory Used: 89 MB
XRAY TraceId: 1-5d811488-cb6c75868f89c9c3377c2d94 SegmentId: 0a6be5452e92a4a7 Sampled: false
```

### Steps to reproduce

**swagger.yaml**
```yaml
openapi: 3.0.1
info:
  title: title
  description: descrip
  version: "0.1"

paths:
  /test:
    get:
      operationId: func.test
      parameters:
        - name: fields
          in: query
          schema:
            type: array
            items:
              type: string
              enum:
              - foo
              - bar
      responses:
        200:
          description: Success
```

**func.py***
```python
def test(*args, **kwargs):

    return 'success!', 200
```

**handler.py**
```python
import connexion, json

c = connexion.App(__name__, specification_dir=".")
app = c.app
c.add_api("swagger.yaml", strict_validation=False)

if __name__ == '__main__':
    app.run()
```

**serverless.yml**
```yaml
service: test

plugins:
  - serverless-python-requirements
  - serverless-wsgi
provider:
  name: aws
  runtime: python3.7

custom:
  wsgi:
    app: handler.app
    pythonBin: python3

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: ANY {proxy+}
```

### Additional info:

Output of the commands:

- `python --version`
- `pip show connexion | grep "^Version\:"`

```
Python 3.7.3
Version: 2.3.0
```

For the time being, I've worked around this by doing [this](https://github.com/zalando/connexion/issues/138#issuecomment-206361679).
