### ISSUE TITLE
Default value for component paramater is not set

### ISSUE THREAD

**Issue by JWDobken** [spec-first/connexion#1184]
The default value set in a parameter of a component is not set.
In this case `piece_count` is a non-required parameter with a default value of 1:

```yaml
components:
  schemas:
    MyObject:
      type: object
        piece_count:
          description: Number of pieces
          type: integer
          format: int64
          default: 1
          example: 1
```

The post request on this schema returns the body without any value for `piece_count`:

```json
{}
```

### Additional info:

- openapi: 3.0.2
- python: 3.7
- connexion==2.4.0
- openapi-spec-validator==0.2.8
