### ISSUE TITLE
x-zally-ignore should be ignored

### ISSUE THREAD

**Issue by zeitlinger** [spec-first/connexion#1229]
### Description

given the following OpenAPI (only a snippet)

```yaml

paths:
  /:
    x-zally-ignore: [143]
    get:

..

      id:
        x-zally-ignore: [174]
        type: integer
        format: int32
        readOnly: true
```

which is meant to ignore a rule from [zally](http://opensource.zalando.com/zally/)

### Expected behaviour

`x-zally-ignore` is ignored

### Actual behaviour

`ERROR:connexion.api:Failed to add operation for X-ZALLY-IGNORE /api/`
