### ISSUE TITLE
A `deepObject` query parameter containing a list is not properly deserialized

### ISSUE THREAD

**Issue by edupo** [spec-first/connexion#1461]
### Description

Deep Object deserialization does not work according to swagger UI. I'm not sure if is a bug or lack of specification on the swagger side.

### Expected behavior

When adding a list inside a `deepObject` query parameter like: `{'foo': { 'bar': [1, 2, 3, 4]}}` the server side must receive the same object.

### Actual behavior

Only one element of the list `bar` list is deserialized.

### Steps to reproduce

- A simple endpoint requiring a query parameter with style `deepObject`

```
components:
  schemas: {}
  parameters:
    foo:
      name: foo
      in: query
      required: false
      style: deepObject
      explode: true
      schema: {}
```

- Send this query:
`?[foo][bar]=1&[foo][bar]=2&[foo][bar]=3&[foo][bar]=4`

- On the server side `foo['bar']` is not a `list`

### Additional info:

The query string can be easily created with the Swagger UI. And they encode lists in `deepObject` like that. But from their [documentation](https://swagger.io/docs/specification/serialization/) is not clear to me how the `deepObject` serialization must work in the lists... It looks like they fall back to their standard behaviour for exploded arrays.

Output of the commands:

- `python --version`
  `Python 3.7.3`
- `pip show connexion | grep "^Version\:"`
  `Version: 2.7.0`
