### ISSUE TITLE
object schema for query parameters not validated

### ISSUE THREAD

**Issue by ddurham2** [spec-first/connexion#1476]
### Description
As best I can tell, if a query parameter has an object-type schema, connexion does not validate it according to that schema, like it post for a POST body, for example.

### Expected behaviour
The openapi spec appears to allows object-type schema for any type of parameters (query or otherwise).

### Actual behaviour
The schema for the query parameter seem to be mostly ignored.

### Steps to reproduce
declare any query parameter with an object-type schema:
```
...
  parameters:
    - name myobj
      in: query
      schema:
        type: object
        properties:
          foo:
            type: string
            maxLength: 64
         bar:
           type: string
             maxLength: 10
```

Such a myobj query parameter is not validated as an object

### Additional info:
I have not looked into what a fix would look like yet, but is there any reason for this not to be supported, or is it an oversight?

Output of the commands:

- `python --version` == 3.8.10
- `pip show connexion | grep "^Version\:"` == 2.12.0
