### ISSUE TITLE
Boolean query parameter with allowEmptyValue responds 400 insisting on `=true` 

### ISSUE THREAD

**Issue by OJFord** [spec-first/connexion#1538]
### Description

A Boolean query parameter with `allowEmptyValue: true` does not allow an empty (i.e. `?param`) value; instead returning 400 Boolean expected.

### Expected behaviour

`/api/blah?allowedEmptyBooleanParam` should work

### Actual behaviour

```
{
	"detail": "Wrong type, expected 'boolean' for query parameter 'allowedEmptyBooleanParam'",
	"status": 400,
	"title": "Bad Request",
	"type": "about:blank"
}
```

### Steps to reproduce

```
    allowedEmptyBooleanParam:
      name: allowedEmptyBooleanParam
      in: query
      schema:
        type: boolean
        default: false
      allowEmptyValue: true
```

### Additional info:

Output of the commands:

- `python --version` `Python 3.10.4`
- `pip show connexion | grep "^Version\:"` `Version: 2.13.0`
