### ISSUE TITLE
date-time format is not validated anymore

### ISSUE THREAD

**Issue by chrismaes87** [spec-first/connexion#1562]
### Description
with the release 2.12.0, openapi-spec-validator was dropped (https://github.com/spec-first/connexion/pull/1455). When specifying a property with format 'date-time', this is not validated anymore, although `strict-rfc3339` is installed

### Expected behaviour
posting a date-time property with bad format sends a response status 400.

### Actual behaviour
No status 400 is sent, the format is not validated

### Steps to reproduce
install:
- (tested also with 2.14.0)
- strict-rfc3339 (version 0.7)

use a schema with date-time format, example:
```
    MyObject:
      type: object
      properties:
        start_time:
          description: Start time (RFC 3339 format).
          type: string
          format: date-time
```

perform a request with this object in the body, and with a bad date-time format.

### Additional info:
versions:
- python 3.9.12
- connexion[swagger-ui] >= 2.12.0
- strict-rfc3339 0.7
