### ISSUE TITLE
How do I use JSON content instead of schema in GET request?

### ISSUE THREAD

**Issue by mdylan2** [spec-first/connexion#1612]
### Description
Swagger UI says that we can wrap schema into `content.media-type` in GET request instead of using only `schema`. However, mapping the content.media-type to function arguments in Connexion doesn't seem to work. Am I doing something wrong?

Here's a snap of the error:
```
python3.8/site-packages/connexion/operations/openapi.py", line 430, in _get_val_from_param
    query_schema = query_defn["schema"]
KeyError: 'schema'
```

Here's a sample path config:
```
/trial:
    get:
        operationId: test
        parameters:
          - name: filter
            in: query
            description: Filters on data
            required: false
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    id:
                      type: string
                      example: hello
```

Here's a sample function:
```
def test(filter={}):
    return filter
```

Connexion Version: 2.14.1
Python 3.8.5
