### ISSUE TITLE
Connextion 3 does not support `object query parameters` correctly

### ISSUE THREAD

**Issue by mmohaveri** [spec-first/connexion#1685]
### Description
I have a OpenAPI spec that has a object query parameter:

```yaml
parameters:
  - name: object_quety
    in: query
    required: false
    schema:
      type: object
      properties:
        p1:
          type: object
          properties:
            b1:
              type: boolean
              default: true
            s1:
              type: string
```

When I send a request to the path of this parameter without any `object_query` parameter, it works as expected, and in my route I get a dictionary with default values of the `object_query`, i.e: `{"p1": {"b1": True}}` as a named paramter.

The problem is that when passing the object query in the URL, the connexion's  validator raises an error. For example if I send an empty object:`?object_query={}` I will get the following error:

```
'{}' is not of type 'object'

Failed validating 'type' in schema:
    {'properties': {'p1': {'properties': {'b1': {'default': True, 'type': 'boolean'},  's1': {'type': 'string'}}, 'type': 'object'}}, 'type': 'object'}

On instance:
    '{}'
```

I think the problem is that the type checker is not passing the query parameter through a `json.loads`, and is being given the string representation of the query instead of a dictionary with its values.

### Additional info:

Output of the commands:

- `python --version`: 3.11.2
- `pip show connexion | grep "^Version\:"` 3.0.0a4
