### ISSUE TITLE
Validation fails for optional datetime query parameter

### ISSUE THREAD

**Issue by mbmccoy** [spec-first/connexion#1732]
### Description
I'm looking for help with an error when validating a non-required query parameter with `datetime` type using OpenAPI 3.0.0.

```yaml
# parameter definition
name: as_of
in: query
description: |
  The end time of the period to return results for. Defaults to
  the current time.
required: false
schema:
  type: string
  format: date-time
  nullable: true
```

Call to endpoint without any query parameters fails with:

```python
{
    'detail': "None is not of type 'string'\n\nFailed validating 'type' in schema['properties']['as_of']:\n    {'description': 'Timestamp of the first observation in the sequence.',\n     'format': 'date-time',\n     'type': 'string'}\n\nOn instance['as_of']:\n    None", 
    'status': 500, 
    'title': 'Response body does not conform to specification', 
    'type': 'about:blank'
}
```

### Expected behaviour

Validates a datetime string or a missing query parameter.

### Actual behaviour

See 500 error above.

### Steps to reproduce

Call endpoint without query parameters.

### Additional info:

Output of the commands:

- `python --version`: 3.9.10
- `pip show connexion | grep "^Version\:"` 2.14.2
- OpenAPI v 3.0.0
