### ISSUE TITLE
Execution Order Issue: before_request Executing After x-apikeyInfoFunc Authentication Method

### ISSUE THREAD

**Issue by oyeamit** [spec-first/connexion#1878]
### Description

I've encountered an issue where Flask's @app.before_request handlers are executing after the authentication method specified by x-apikeyInfoFunc in my Connexion 3 application. This behavior is contrary to my expectations (using Connexion 2) where I assumed before_request handlers should run before any authentication logic, allowing for pre-processing of requests regardless of their authentication state.

### Expected behaviour

I expected that the @app.before_request handlers would execute before any authentication logic, allowing for request pre-processing such as logging, request modification, or other preliminary checks.

### Actual behaviour

The @app.before_request handlers are executed after the authentication method specified by x-apikeyInfoFunc, limiting the ability to perform certain actions before the authentication step.

### Steps to reproduce

1. Define an authentication method and reference it in the OpenAPI specification using x-apikeyInfoFunc.
2. Implement a Flask @app.before_request handler for pre-processing requests.
3. Observe the order of execution when making requests to protected endpoints.

### Additional info:

```
# Example snippet from OpenAPI specification showing the security definition
securitySchemes:
  ApiKeyAuth:
    type: apiKey
    in: header
    name: X-API-Key
    x-apikeyInfoFunc: my_auth_func
```

```
@app.before_request
def before_request_func():
    # Expected to run before authentication
    print("This should execute before authentication")
```

Output of the commands:

- `Python 3.10.9`
- `Connexion 3.0.5`
- `Flask 2.2.5`
- `Werkzeug 2.3.8`
