### ISSUE TITLE
Allow customization of validator / Apply defaults in request body

### ISSUE THREAD

**Issue by phoracek** [spec-first/connexion#351]
### Description

I need Connexion to use default value if a property is missing in request body. Although it is done with URL query, in body 'default' is just for documentation purposes (that is nature of JSON Schema). In order to enforce defaults (as described here https://python-jsonschema.readthedocs.io/en/latest/faq/#why-doesn-t-my-schema-that-has-a-default-property-actually-set-the-default-on-my-instance) I need to overwrite validator used in `connexion/decorators/validation.py`. It would be even better if Connexion offered defaults enforcement on its own.

### Expected bahaviour

- Access to body validation class in similar way as we have it with Resolver.

OR

- A flag to set 'defaults enforcement'. When 'defaults' is defined for a non-required property and the property is not passed, default value should be used.

### Actual behaviour

We don't have tools for that. When non-required property is not passed, it is not included in data provided for controlled function, even if there are defaults.

### Example

```yaml
...
    post:
      operationId: "controllers.post_foo"
      parameters:
      - in: "body"
        name: "foo"
        required: true
        schema:
          $ref: "#/definitions/Foo"
      responses:
        200:
          description: "OK"
definitions:
  Foo:
    type: "object"
    properties:
      name:
        type: "string"
        default: "BOB"
```

If `-d '{}'` was sent, controller should receive `{'name': 'BOB'}`.

### Another example

It should be enough to provide defaults in bottom-most layer.

```yaml
definitions:
  Foo:
    type: "object"
    default: {}
    properties:
      name:
        type: "object"
        properties:
          first:
            type: "string"
            default: "BOB"
          last:
            type: "string"
            default: "DOE"
```

If `-d '{}'` was sent, controller should receive `{'name': {'first': 'BOB', 'last': 'DOE'}}`.
