### ISSUE TITLE
Swagger UI index.html clientId configurable from oauth security definition

### ISSUE THREAD

**Issue by kfkelvinng** [spec-first/connexion#549]
### Description
Swagger UI index.html clientId configurable from oauth security definition

https://github.com/zalando/connexion/blob/f4bc6dc71b5863f9d4a6e3ec5822dd4a46381421/connexion/vendor/swagger-ui/index.html#L59-L66

### Expected behaviour

Able to define client_id from swagger yml

```
securityDefinitions:
  oauth2:
    type: oauth2
    flow: implicit
    authorizationUrl: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
    clientId: xxx
```

### Actual behaviour
clientId is not configurable

### Additional info:

Related: https://github.com/swagger-api/swagger-ui/issues/2897
