### ISSUE TITLE
How to debug Automatic Routing with RestyResolver?

### ISSUE THREAD

**Issue by trickidicki** [spec-first/connexion#784]
I'm struggling to use automatic routing with RustyResolver.

I have two endpoints:

```
paths:
  /members:
    get:
...
  /members/{id}:
    get:
```

I have the code implemented in `api/members.py`:

```
<snip>
def get(memberId):
    import traceback
    traceback.print_stack()
    print("Hello from members/get")
    id_ = int(memberId)
    if members.get(id_) is None:
        return NoContent, 404
    return members[id_]


def search(limit=100):
    # NOTE: we need to wrap it with list for Python 3 as dict_values is not JSON serializable
    return list(members.values())[0:limit]
```

The call to `/members` works fine, the call to `/members/1` doesn't get routed and generates a 404.

Any suggestions?

**Comment by trickidicki** [comment]
I have found the cause of the problem - the YAML specifies 

```
  /members/{id}:
    get:
      parameters:
        - description: Unique identifier for the member
          example: '1'
          in: path
          name: id
          required: true
          schema:
            type: number
```
This then registered a route expecting a float, not an int.

So `/api/member/1.0` works but `/api/member/1` doesn't.

Note this is using `connexion.FlaskApp()`
