### ISSUE TITLE
Connexion 2.0 - Cookie Authentication Support

### ISSUE THREAD

**Issue by Guru67724** [spec-first/connexion#791]
Hi All,

I have just started to use Connexion 2.0. I am looking for security mechanisms. Meanwhile i went through OpenApi 3 docs where i found 'Cookie Authentication'. 
https://swagger.io/docs/specification/authentication/cookie-authentication/

Can you please let me know whether cookie auth support was included in the current connexion release or not. Bcos i get '**No Authorization token found'** error when i declare the following in yaml file.

cookieAuth:        
      type: apiKey
      in: **cookie**
      name: my-secret
      x-apikeyInfoFunc: app_manager_api.fun

Later found that verify_apikey() function in connexion/decorators/security.py file handles only apiKey support in 'header' and 'query'. So is it understood that apiKey in cookie is not supported so far...?

One more question (may be silly),
I found the following line in verify_security() function in connexion/decorators/security.py file.
request.context['user'] = token_info.get('**sub**', token_info.get('uid'))
My doubt here is what is the significance of using the word '**sub**' here. Because in all examples i could see, a dict of form {'sub':'foo'} is returned in all authentication verification functions.

Thanks
GuruPrasad

**Comment by dtkav** [comment]
hey @Guru67724  - cookie auth is not yet supported, but have a look at #794 .
I'm not sure about your final question, maybe @krise3k has some thoughts?

**Comment by Guru67724** [comment]
Hi @dtkav - Thank you very much. Yes #794 is what i was looking for. Hope it helps.

And for the other query, just curious to know what is the reference to the word 'sub' used there. Nothing else.

**Comment by krise3k** [comment]
@Guru67724 its from oauth  token introspection RFC https://tools.ietf.org/html/rfc7662#section-2.2

**Comment by Guru67724** [comment]
@krise3k . Thank you very much. So it is just a standard format representing the subject of the cookie/token.

**Comment by kmekilo** [comment]
When do you think cookie auth will be supported by connexion?

**Comment by M0dM** [comment]
Hi,

I can confirm this is working just fine with connexion 2.6.0.

Please find below some code sample.
It might be useful to add some doc about it.

```yaml
      security:
        - jwt: ['secret']
        - api_key : []

[...]

components:
  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
      x-bearerInfoFunc: functions.decode_token
    api_key:
      type: apiKey
      name: auth_token
      in: cookie
      x-apikeyInfoFunc: functions.decode_cookie
```
