### ISSUE TITLE
OAuth2 Authorization Code support

### ISSUE THREAD

**Issue by smn-snkl** [spec-first/connexion#858]
### Description
I need to secure my app with OAuth2's Authorization Code grant and I'm wondering what the best way is to integrate this OAuth scheme with connexion. Is there already a way to adapt the OAuth2 Implicit and / or Bearer token features to achieve the Authorization Code method? Should I use something like flask-oauthlib? If so, how would one integrate the views into connexion?

**Comment by smn-snkl** [comment]
More specifically, I've implemented it with [authlib](https://docs.authlib.org/en/latest/flask/2/resource-server.html) before, so now I'm wondering how I would make sure the views are decorated correctly (e.g. in this case there's a `require_oauth` decorator that's used)

**Comment by dtkav** [comment]
Hey @smn-snkl - I'm not that familiar with oauth2, but I'll do my best to help.

Note that connexion applies a security decorator as the first step in decoding a request, so you'll want to hook in there rather than using security decorators on the handler function (as that would open you up to vulnerabilities in all the code that runs before the handler function).

For oauth2 there's an example here:
https://github.com/zalando/connexion/tree/master/examples/swagger2/oauth2_local_tokeninfo

You define an `x-tokenInfoFunc`, which points to the handler function which is responsible for getting the token and scopes from the request.
```
securityDefinitions:
  oauth2:
    type: oauth2
    flow: implicit
    authorizationUrl: https://example.com/oauth2/dialog
    x-tokenInfoFunc: app.token_info
    scopes:
      uid: Unique identifier of the user accessing the service.
```
You'll want to do your oauth logic in the "token info func", which is discovered with the same mechanism as `operationId`s.
```
def token_info(access_token) -> dict:
    uid = TOKENS.get(access_token)
    if not uid:
        return None
    return {'uid': uid, 'scope': ['uid']}
```

Hope that helps!

**Comment by smn-snkl** [comment]
Thanks @dtkav, I wasn't sure how to move from authlib's require_oauth(scopes, operator, optional) decorator to a token_info(access_token) function.

So now I'm trying to implement it like this:

```
def oauth_token_info(access_token):
    token = Token.objects.get(access_token=access_token)
    return {'sub': token.user, 'scope': token.scope}


def oauth_validate_scope(required_scopes, token_scopes):
    try:
        token = require_oauth.acquire_token(scope=" ".join(required_scopes))
    except Exception:
        token = None

    if token:
        return True

    return False
```

And then in the openapi.yml:

```
components:
  securitySchemes:
    oauth2:
      type: oauth2
      x-tokenInfoFunc: app.common.auth.oauth_token_info
      x-scopeValidateFunc: app.common.auth.oauth_validate_scope
      flows:
        authorizationCode:
          authorizationUrl: /oauth/authorize/
          tokenUrl: /oauth/token/
          refreshUrl: /oauth/token/
          scopes: {}
```

Does that make sense?

However, now I'm struggeling to test it, because I can't change the `oauth2RedirectUrl` configuration parameter for `swagger-ui` which is always redirecting to /oauth-redirect.html but it should redirect to /ui/oauth-redirect.html as `connexion` but's swagger-ui under /ui/

Any help on that?
