### ISSUE TITLE
Maximum & minimum does not work at parameters

### ISSUE THREAD

**Issue by lovesuper** [spec-first/connexion#882]
### Description

```
limit:
  description: The number of items to return
  in: query
  name: limit
  required: true
  schema:
    type: integer
    minimum: 1
    maximum: 1000

```
### Expected behaviour

Numbers above and below 1 and 1000 must to decline by server

### Actual behaviour

They are being accepted

### Steps to reproduce

Just try to validate integer by `maximum` and `minimum` at parameters

### Additional info:

Output of the commands:

- `Python 3.7.2`
- `Version: 2018.0.dev1`
